services:
  test-db:
    image: 'postgres:15'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: starship-fighters-test
    ports:
      - '5443:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
volumes:
  postgres_test_data: ~
