services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: starship-fighters
    ports:
      - '5442:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: ~
