-- AlterTable
ALTER TABLE "people" ADD COLUMN     "birthYear" INTEGER NOT NULL DEFAULT 1993,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "eyeColor" TEXT NOT NULL DEFAULT 'green',
ADD COLUMN     "hairColor" TEXT NOT NULL DEFAULT 'black',
ADD COLUMN     "height" INTEGER NOT NULL DEFAULT 185,
ADD COLUMN     "homeworld" TEXT NOT NULL DEFAULT 'earth',
ADD COLUMN     "skinColor" TEXT NOT NULL DEFAULT 'white',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;