-- CreateEnum
CREATE TYPE "StarshipClass" AS ENUM ('FIGHTER', 'TRANSPORTER', 'SPEEDER');

-- AlterTable
ALTER TABLE "starships" ADD COLUMN     "cargoCapacity" INTEGER NOT NULL,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "hyperdriveRating" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "length" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "maxSpeed" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "model" TEXT NOT NULL DEFAULT gen_random_uuid(),
ADD COLUMN     "starshipClass" "StarshipClass" NOT NULL DEFAULT 'FIGHTER',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- CreateIndex
CREATE UNIQUE INDEX "starships_model_key" ON "starships"("model");
